### ISSUE TITLE
darkice-1.0 fails to compile with gcc-4.4 with certain ./configure flags

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rafael2k/darkice#29]
```
What steps will reproduce the problem?
1. ./configure --without-vorbis --without-faac --without-aacplus 
--without-twolame --without-alsa --without-jack --without-samplerate --with-lame
2. make

What do you see instead?

x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I.    -O2 -pedantic -Wall  -pthread 
-march=core2 -msse4.1 -O2 -pipe -c -o TcpSocket.o TcpSocket.cpp
SerialUlaw.cpp: In member function ‘virtual unsigned int 
SerialUlaw::read(void*, unsigned int)’:
SerialUlaw.cpp:296:26: error: ‘perror’ was not declared in this scope

What version of the product are you using? On what operating system?

GNU GCC 4.4.x / Linux+glibc

Please provide any additional information below.

Missing #include <stdio.h> for perror, patch attached.
```

Original issue reported on code.google.com by `ssuomi...@unk.fi` on 29 Jul 2010 at 11:52

Attachments:
- [darkice-1.0-gcc44.patch](https://storage.googleapis.com/google-code-attachments/darkice/issue-29/comment-0/darkice-1.0-gcc44.patch)
