### ISSUE TITLE
Darkice fails to compile on Ubuntu 12.04 LTS "precise"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rafael2k/darkice#67]
```
What steps will reproduce the problem?
1. Install jackd and libraries (either v0 or v2) on an otherwise vanilla 
install of Ubuntu 12.04 "precise" on a powerpc machine.
2. Checkout latest read-only svn of darkice (rev. 505 as of writing)
3. Run ./configure -with-jack (along with any other addins and the prefix 
switches for make to look in /usr/lib/{arch}-linux-gnu for the necessary 
libraries)
4. Run make

What is the expected output? What do you see instead?
Expected output: darkice compiles without error.

Instead, the user gets:

make[2]: Entering directory `/home/usernm/Downloads/darkice-read-only/src'
g++ -DHAVE_CONFIG_H -I. -I -I  -I -I -I   -O2 -pedantic -Wall  -pthread -g -O2 
-MT JackDspSource.o -MD -MP -MF .deps/JackDspSource.Tpo -c -o JackDspSource.o 
JackDspSource.cpp
JackDspSource.cpp: In member function âvirtual bool JackDspSource::open()â:
JackDspSource.cpp:204:56: error: âsnprintfâ was not declared in this scope
JackDspSource.cpp:206:56: error: âsnprintfâ was not declared in this scope
make[2]: *** [JackDspSource.o] Error 1
make[2]: Leaving directory `/home/usernm/Downloads/darkice-read-only/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/usernm/Downloads/darkice-read-only/src'
make: *** [all-recursive] Error 1


What version of the product are you using? On what operating system?
* Darkice revision 505 from the read-only svn
* Vanilla install of precise pangolin (along with jackd, as stated above) on a 
powerpc architecture 

Please provide any additional information below.

I'm not sure if this is a bug in the version of g++ for the ppc architecture or 
what; regardless, putting a #include<stdio.h> as the first uncommented line in 
darkice-read-only/src/JackDspSource.cpp allowed the make to run without any 
further errors.

This could be fixed with a simple patch; and even if it is just a g++ or 
architecture-specific error, the #include shouldn't hurt anything...

```

Original issue reported on code.google.com by `jakeno...@gmail.com` on 14 May 2012 at 12:49
